// Location State Data - Indian States and Cities
export const LocationStateData = {
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijayawada',
    'Tirupati',
    'Amaravati',
    'Nellore',
    'Ongole',
    'Eluru',
    'Guntur',
    'Tadepalligudem',
    'Tenali',
  ],
  'Arunachal Pradesh': [
    'Itanagar',
    'Pasighat',
    'Tawang',
    'Naharlagun',
    'Tezu',
    'Changlang',
    'Bomdila',
  ],
  'Assam': [
    'Guwahati',
    'Dispur',
    'Silchar',
    'Dibrugarh',
    'Barpeta',
    'Nagaon',
    'Sonitpur',
    'Karimganj',
    'Dhubri',
  ],
  'Bihar': [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Munger',
    'Motihari',
    'Arrah',
    'Darbhanga',
    'Madhuban',
    'Gopalganj',
  ],
  'Chhattisgarh': [
    'Raipur',
    'Durg',
    'Bilaspur',
    'Rajnandgaon',
    'Jagdalpur',
    'Korba',
    'Dhamtari',
    'Kondagaon',
  ],
  'Goa': [
    'Panaji',
    'Margao',
    'Ponda',
    'Vasco da Gama',
    'Pernem',
    'Bicholim',
    'Sattari',
    'Sanguem',
  ],
  'Gujarat': [
    'Ahmedabad',
    'Vadodara',
    'Surat',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Junagadh',
    'Anand',
    'Gandhinagar',
    'Porbandar',
    'Baroda',
    'Kutch',
    'Dasuya',
    'Palanpur',
    'Godhra',
  ],
  'Haryana': [
    'Faridabad',
    'Gurgaon',
    'Hisar',
    'Rohtak',
    'Karnal',
    'Panipat',
    'Ambala',
    'Yamunanagar',
    'Bhiwani',
  ],
  'Himachal Pradesh': [
    'Shimla',
    'Mandi',
    'Kangra',
    'Solan',
    'Bilaspur',
    'Kinnaur',
    'Chamba',
    'Hamirpur',
    'Una',
  ],
  'Jharkhand': [
    'Ranchi',
    'Dhanbad',
    'Giridih',
    'Jamshedpur',
    'Hazaribagh',
    'Bokaro',
    'Deoghar',
    'Godda',
    'Dumka',
  ],
  'Karnataka': [
    'Bangalore',
    'Mysore',
    'Mangalore',
    'Belgaum',
    'Hubballi',
    'Davangere',
    'Gulbarga',
    'Hassan',
    'Chikmagalur',
    'Shimoga',
  ],
  'Kerala': [
    'Thiruvananthapuram',
    'Ernakulam',
    'Thrissur',
    'Kannur',
    'Kozhikode',
    'Pathanamthitta',
    'Alappuzha',
    'Idukki',
    'Kottayam',
  ],
  'Madhya Pradesh': [
    'Indore',
    'Bhopal',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Ratlam',
    'Satna',
    'Dewas',
  ],
  'Maharashtra': [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Aurangabad',
    'Nashik',
    'Akola',
    'Amravati',
    'Kolhapur',
    'Solapur',
    'Thane',
  ],
  'Manipur': [
    'Imphal',
    'Imphal West',
    'Imphal East',
    'Bishnupur',
    'Thoubal',
    'Ukhrul',
    'Tamenglong',
    'Senapati',
  ],
  'Meghalaya': [
    'Shillong',
    'Tura',
    'Cherrapunji',
    'Jaintia Hills',
    'Khasi Hills',
    'Garo Hills',
    'Nongpoh',
  ],
  'Mizoram': [
    'Aizawl',
    'Lunglei',
    'Saiha',
    'Champhai',
    'Kolasib',
    'Lawngtlai',
    'Mamit',
  ],
  'Nagaland': [
    'Kohima',
    'Dimapur',
    'Wokha',
    'Mon',
    'Tuensang',
    'Longleng',
    'Kiphire',
    'Zunheboto',
  ],
  'Odisha': [
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    'Sambalpur',
    'Balasore',
    'Bargarh',
    'Berhampur',
    'Dhenkanal',
  ],
  'Punjab': [
    'Chandigarh',
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Hoshiarpur',
    'Pathankot',
    'Malerkotla',
  ],
  'Rajasthan': [
    'Jaipur',
    'Jodhpur',
    'Udaipur',
    'Kota',
    'Bikaner',
    'Ajmer',
    'Alwar',
    'Bhilwara',
    'Churu',
    'Dungarpur',
  ],
  'Sikkim': [
    'Gangtok',
    'Namchi',
    'Gyalshing',
    'Mangan',
    'Pelling',
    'Ravangla',
    'Singtam',
  ],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Salem',
    'Tiruchirapalli',
    'Tirunelveli',
    'Kanyakumari',
    'Kanniyakumari',
    'Vellore',
  ],
  'Tripura': [
    'Agartala',
    'Udaipur',
    'Ambassa',
    'Kailasahar',
    'Dharmanagar',
    'Sabroom',
    'Komaram Bheem',
  ],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Agra',
    'Varanasi',
    'Meerut',
    'Allahabad',
    'Bareilly',
    'Saharanpur',
    'Mathura',
    'Ghaziabad',
  ],
  'Uttarakhand': [
    'Dehradun',
    'Nainital',
    'Haridwar',
    'Rudraprayag',
    'Chamoli',
    'Almora',
    'Bageshwar',
    'Pithoragarh',
  ],
  'West Bengal': [
    'Kolkata',
    'Howrah',
    'Darjeeling',
    'Asansol',
    'Siliguri',
    'Jalpaiguri',
    'Malda',
    'Kharagpur',
    'Durgapur',
  ],
  'Telangana': [
    'Hyderabad',
    'Secunderabad',
    'Warangal',
    'Karimnagar',
    'Khammam',
    'Mahbubnagar',
    'Medak',
    'Nizamabad',
  ],
  'Ladakh': [
    'Leh',
    'Kargil',
  ],
  'Jammu and Kashmir': [
    'Srinagar',
    'Jammu',
    'Anantnag',
    'Baramulla',
    'Samba',
    'Udhampur',
    'Leh',
  ],
  'Delhi': [
    'New Delhi',
    'Delhi Cantt',
    'South Delhi',
    'East Delhi',
    'West Delhi',
    'North Delhi',
  ],
  'Puducherry': [
    'Pondicherry',
    'Yanam',
    'Mahe',
    'Karaikal',
  ],
  'Lakshadweep': [
    'Kavaratti',
    'Agatti',
    'Androth',
    'Minicoy',
  ],
  'Andaman and Nicobar Islands': [
    'Port Blair',
    'Campbell Bay',
    'Rangat',
    'Nancowry',
  ],
  'Daman and Diu': [
    'Daman',
    'Diu',
  ],
  'Dadra and Nagar Haveli': [
    'Silvassa',
    'Dadra',
  ],
};

// Helper function to get cities for a state
export const getCitiesForState = (state: string): string[] => {
  return LocationStateData[state as keyof typeof LocationStateData] || [];
};

// Helper function to validate state and city combination
export const isValidStateCity = (state: string, city: string): boolean => {
  const citiesForState = getCitiesForState(state);
  return citiesForState.includes(city);
};

// Get all states
export const getAllStates = (): string[] => {
  return Object.keys(LocationStateData).sort();
};